# General site settings
title: Sulochan Thapa
description: Sulochan Thapa is a Local Digital Marketing Expert and Software Developer specializing in Google SEO, AI-powered SEO strategies, website development, and custom software solutions. With hands-on experience in frontend and backend development, deployment, web security, and performance optimization, Sulochan helps businesses build high-performing digital platforms and grow their online presence.
keywords: "Sulochan Thapa, digital marketing expert, SEO expert, Google SEO, AI SEO, website developer, software developer, full stack developer, frontend development, backend development, website optimization, web security, performance optimization, site deployment, web developer Sikkim, Indian freelancer, local SEO, website design India"
author: "Sulochan Thapa"
author: "Sulochan Thapa"
url: "https://sulochanthapa.github.io"
baseurl: "" # optional, used for site deployed in a subdirectory

defaults:
  - scope:
      path: "sitemap.xml"
    values:
      layout: "none"
  - scope:
      path: "thankyou"
    values:
      sitemap: "false"
  - scope:
      path: "googlebfdf74e9e9477ded.html"
    values:
      sitemap: "false"

# Author settings
author: "Sulochan Thapa"

# Social links
social:
  github: https://github.com/sulochanthapa

# Markdown settings
markdown: kramdown

# Theme settings (if using a theme)
#theme: minimal

# Plugins (if applicable)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
exclude:
  - "README.md"   # Exclude files/folders from the build
  - "LICENSE"

# Analytics settings (for Google Analytics or others)
# google_analytics: UA-XXXXX-X

# Permalink settings (for post URLs)
permalink: blog/:title/

# permalink: /:year/:month/:day/:title/
# Collections settings (for post URLs)
collections:
  projects:
    output: true
    permalink: /project/:title/
# RSS feed settings
feed:
  path: "feed.xml"
  limit: 10
